//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delegate.GhettoTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Delegate.GhettoTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 79.110.94.211 EU Killian,
        ///79.110.94.212 EU Fraya,
        ///79.110.94.213 EU Hasmina,
        ///79.110.94.214 EU Elinu,
        ///79.110.94.215 EU Icaruna,
        ///79.110.94.216 EU Veritas,
        ///79.110.94.217 EU Akasha,
        ///79.110.94.218 EU Arcadia,
        ///79.110.94.219 EU Kaidun,
        ///119.205.255.106 KR Mystelle,
        ///119.205.255.118 KR Bellick,
        ///119.205.255.119 KR Arun,
        ///208.67.49.28 NA Tempest Reach,
        ///208.67.49.52 NA Lake of Tears,
        ///208.67.49.68 NA Celestial Hills,
        ///208.67.49.84 NA Ascension Valley,
        ///208.67.49.92 NA Mount Tyrannas,
        ///208.67.49.100 NA Valley of Titans,
        ///208.67 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Servers {
            get {
                return ResourceManager.GetString("Servers", resourceCulture);
            }
        }
    }
}
