//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delegate.Meter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Delegate.Meter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_TELEPORT = 0
        ///I_SPAWN_BARRACK_CHARACTER = 1
        ///R_PLAYER_LOCATION = 2
        ///R_TELEPORT_REPLAY_LOCATION = 3
        ///R_CAMERA_ROTATE = 4
        ///I_GFX_COMMAND = 17
        ///I_GFX_ADMIN_COMMAND = 18
        ///I_INPUT_COMMAND = 19
        ///I_MOVE_KEY = 20
        ///I_SKILL_KEY = 21
        ///I_CLOSE_SERVER_CONNECTION = 22
        ///SA_PING = 5000
        ///AS_PING = 5001
        ///SA_REGISTER = 5002
        ///AS_REGISTER = 5003
        ///SA_ENTER_WORLD = 5004
        ///SA_ENTER_WORLD_FAIL = 5005
        ///AS_ENTER_WORLD = 5006
        ///AS_LOAD_TOPO_FIN = 5007
        ///SA_TRY_TO_LEAVE_WORLD = 5008
        ///AS_LEAVE_WORLD = 5009
        ///SA_LEAVE_WORLD = 5010
        ///SA_SEND [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _311378 {
            get {
                return ResourceManager.GetString("_311378", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_TELEPORT = 0
        ///I_SPAWN_BARRACK_CHARACTER = 1
        ///R_PLAYER_LOCATION = 2
        ///R_TELEPORT_REPLAY_LOCATION = 3
        ///R_CAMERA_ROTATE = 4
        ///I_GFX_COMMAND = 17
        ///I_GFX_ADMIN_COMMAND = 18
        ///I_INPUT_COMMAND = 19
        ///I_MOVE_KEY = 20
        ///I_SKILL_KEY = 21
        ///I_CLOSE_SERVER_CONNECTION = 22
        ///SA_PING = 5000
        ///AS_PING = 5001
        ///SA_REGISTER = 5002
        ///AS_REGISTER = 5003
        ///SA_ENTER_WORLD = 5004
        ///SA_ENTER_WORLD_FAIL = 5005
        ///AS_ENTER_WORLD = 5006
        ///AS_LOAD_TOPO_FIN = 5007
        ///SA_TRY_TO_LEAVE_WORLD = 5008
        ///AS_LEAVE_WORLD = 5009
        ///SA_LEAVE_WORLD = 5010
        ///SA_SEND [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _311380 {
            get {
                return ResourceManager.GetString("_311380", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_TELEPORT = 0
        ///I_SPAWN_BARRACK_CHARACTER = 1
        ///R_PLAYER_LOCATION = 2
        ///R_TELEPORT_REPLAY_LOCATION = 3
        ///R_CAMERA_ROTATE = 4
        ///I_GFX_COMMAND = 17
        ///I_GFX_ADMIN_COMMAND = 18
        ///I_INPUT_COMMAND = 19
        ///I_MOVE_KEY = 20
        ///I_SKILL_KEY = 21
        ///I_CLOSE_SERVER_CONNECTION = 22
        ///SA_PING = 5000
        ///AS_PING = 5001
        ///SA_REGISTER = 5002
        ///AS_REGISTER = 5003
        ///SA_ENTER_WORLD = 5004
        ///SA_ENTER_WORLD_FAIL = 5005
        ///AS_ENTER_WORLD = 5006
        ///AS_LOAD_TOPO_FIN = 5007
        ///SA_TRY_TO_LEAVE_WORLD = 5008
        ///AS_LEAVE_WORLD = 5009
        ///SA_LEAVE_WORLD = 5010
        ///SA_SEND [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _311738 {
            get {
                return ResourceManager.GetString("_311738", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Zones&gt;
        ///	&lt;Zone id=&quot;0&quot; name=&quot;unknown&quot; &gt;
        ///		&lt;Monster name=&quot;Human Male Warrior&quot; id=&quot;10101&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Human Male Lancer&quot; id=&quot;10102&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Human Male Slayer&quot; id=&quot;10103&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Human Male Berserker&quot; id=&quot;10104&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Human Male Sorcerer&quot; id=&quot;10105&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Human Male Archer&quot; id=&quot;10106&quot; isBoss=&quot;False [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monsters_EU_EN {
            get {
                return ResourceManager.GetString("monsters_EU_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Zones&gt;
        ///	&lt;Zone id=&quot;0&quot; name=&quot;unknown&quot; &gt;
        ///		&lt;Monster name=&quot;Guerrier humain&quot; id=&quot;10101&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Lancier humain&quot; id=&quot;10102&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Pourfendeur humain&quot; id=&quot;10103&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Berserker humain&quot; id=&quot;10104&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Sorcier humain&quot; id=&quot;10105&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Archer humain&quot; id=&quot;10106&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monsters_EU_FR {
            get {
                return ResourceManager.GetString("monsters_EU_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Zones&gt;
        ///	&lt;Zone id=&quot;0&quot; name=&quot;unknown&quot; &gt;
        ///		&lt;Monster name=&quot;Menschenkrieger&quot; id=&quot;10101&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Menschenlanzer&quot; id=&quot;10102&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Menschenzerstörer&quot; id=&quot;10103&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Menschenberserker&quot; id=&quot;10104&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Menschenzauberer&quot; id=&quot;10105&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Menschenbogenschütze&quot; id=&quot;10106&quot; isBoss=&quot;False&quot; hp=&quot;0&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monsters_EU_GER {
            get {
                return ResourceManager.GetString("monsters_EU_GER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Zones&gt;
        ///	&lt;Zone id=&quot;0&quot; name=&quot;unknown&quot; &gt;
        ///		&lt;Monster name=&quot;ヒューマン男ウォーリアー&quot; id=&quot;10101&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;ヒューマン男ランサー&quot; id=&quot;10102&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;ヒューマン男スレイヤー&quot; id=&quot;10103&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;ヒューマン男バーサーカー&quot; id=&quot;10104&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;ヒューマン男ソーサラー&quot; id=&quot;10105&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;ヒューマン男アーチャー&quot; id=&quot;10106&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;ヒューマン男プリースト [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monsters_JP {
            get {
                return ResourceManager.GetString("monsters_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Zones&gt;
        ///	&lt;Zone id=&quot;0&quot; name=&quot;unknown&quot; &gt;
        ///		&lt;Monster name=&quot;휴먼 남 검투사&quot; id=&quot;10101&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;휴먼 남 창기사&quot; id=&quot;10102&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;휴먼 남 무사&quot; id=&quot;10103&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;휴먼 남 광전사&quot; id=&quot;10104&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;휴먼 남 마법사&quot; id=&quot;10105&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;휴먼 남 궁수&quot; id=&quot;10106&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;휴먼 남 사제&quot; id=&quot;10107&quot; isBoss=&quot;Fals [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monsters_KR {
            get {
                return ResourceManager.GetString("monsters_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Zones&gt;
        ///	&lt;Zone id=&quot;0&quot; name=&quot;unknown&quot; &gt;
        ///		&lt;Monster name=&quot;Human Male Warrior&quot; id=&quot;10101&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Human Male Lancer&quot; id=&quot;10102&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Human Male Slayer&quot; id=&quot;10103&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Human Male Berserker&quot; id=&quot;10104&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Human Male Sorcerer&quot; id=&quot;10105&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Human Male Archer&quot; id=&quot;10106&quot; isBoss=&quot;False [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monsters_NA {
            get {
                return ResourceManager.GetString("monsters_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Zones&gt;
        ///	&lt;!-- Ghillede --&gt;
        ///	&lt;Zone id=&quot;713&quot;&gt;
        ///		&lt;Monster id=&quot;81301&quot; isBoss=&quot;True&quot; /&gt;
        ///		&lt;Monster id=&quot;81398&quot; isBoss=&quot;True&quot; /&gt;
        ///		&lt;Monster id=&quot;81399&quot; isBoss=&quot;True&quot; /&gt;
        ///	&lt;/Zone&gt;
        ///	&lt;Zone id=&quot;813&quot;&gt;
        ///		&lt;Monster id=&quot;81301&quot; isBoss=&quot;True&quot; /&gt;
        ///		&lt;Monster id=&quot;81398&quot; isBoss=&quot;True&quot; /&gt;
        ///		&lt;Monster id=&quot;81399&quot; isBoss=&quot;True&quot; /&gt;
        ///	&lt;/Zone&gt;
        ///	
        ///	&lt;!-- Sabex Armory --&gt;
        ///	&lt;Zone id=&quot;808&quot;&gt;
        ///		&lt;Monster id=&quot;20081000&quot; isBoss=&quot;False&quot; /&gt;
        ///		&lt;Monster id=&quot;20081001&quot; isBoss=&quot;False&quot; /&gt;
        ///		&lt;Monster id= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monsters_override {
            get {
                return ResourceManager.GetString("monsters_override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Zones&gt;
        ///	&lt;Zone id=&quot;0&quot; name=&quot;unknown&quot; &gt;
        ///		&lt;Monster name=&quot;Человек-воин (муж.)&quot; id=&quot;10101&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Человек-рыцарь (муж.)&quot; id=&quot;10102&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Человек-убийца (муж.)&quot; id=&quot;10103&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Человек-берсерк (муж.)&quot; id=&quot;10104&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Человек-маг (муж.)&quot; id=&quot;10105&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;Человек-лучник (муж.)&quot; id=&quot;10106&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monsters_RU {
            get {
                return ResourceManager.GetString("monsters_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Zones&gt;
        ///	&lt;Zone id=&quot;0&quot; name=&quot;unknown&quot; &gt;
        ///		&lt;Monster name=&quot;人類(男)劍鬥士&quot; id=&quot;10101&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;人類(男)槍騎士&quot; id=&quot;10102&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;人類(男)屠殺者&quot; id=&quot;10103&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;人類(男)狂戰士&quot; id=&quot;10104&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;人類(男)魔導士&quot; id=&quot;10105&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;人類(男)弓箭手&quot; id=&quot;10106&quot; isBoss=&quot;False&quot; hp=&quot;0&quot; /&gt;
        ///		&lt;Monster name=&quot;人類(男)祭司&quot; id=&quot;10107&quot; isBoss=&quot;Fa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monsters_TW {
            get {
                return ResourceManager.GetString("monsters_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 79.110.94.211 EU Killian,
        ///79.110.94.212 EU Mystel,
        ///79.110.94.213 EU Yurian,
        ///79.110.94.214 EU Seren,
        ///
        ///208.67.49.28 NA Tempest Reach,
        ///208.67.49.68 NA Celestial Hills,
        ///208.67.49.84 NA Ascension Valley,
        ///208.67.49.93 NA Mount Tyrannas,
        ///208.67.49.60 NA Fey Forest,
        ///
        ///91.225.237.5 RU Кайа,
        ///91.225.237.6 RU Велика,
        ///
        ///183.110.3.6 KR 아룬의 영광,
        ///183.110.3.7 KR 카이아의 가호
        ///.
        /// </summary>
        internal static string servers {
            get {
                return ResourceManager.GetString("servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMT_UNDEFINED = 0
        ///SMT_LOBBY_CANNOT_CONNECT = 1
        ///SMT_LOBBY_CONFIRM_DISCONNECT = 2
        ///SMT_LOBBY_CHARACTER_FULL = 3
        ///SMT_LOBBY_CONFIRM_DELETE_CHARACATER = 4
        ///SMT_LOBBY_DELETE_CHARACATER_COMPLETE = 5
        ///SMT_LOBBY_CONFIRM_CANCEL_DELETE_CHARACATER = 6
        ///SMT_LOBBY_CANCEL_DELETE_CHARACATER_COMPLETE = 7
        ///SMT_LOBBY_DUPLICATE_NAME = 8
        ///SMT_LOBBY_CHARACTER_NAME_LIMIT = 9
        ///SMT_LOBBY_CHARACTER_NAME_FORBIDDEN = 10
        ///SMT_LOBBY_CHARACTER_NAME_OK = 11
        ///SMT_LOBBY_CONFIRM_CREATE_CHARACTER = 12
        ///SMT_LOBBY_CHARACTER_NAME_SPECIAL_LETT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string smt_311378 {
            get {
                return ResourceManager.GetString("smt_311378", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMT_UNDEFINED = 0
        ///SMT_LOBBY_CANNOT_CONNECT = 1
        ///SMT_LOBBY_CONFIRM_DISCONNECT = 2
        ///SMT_LOBBY_CHARACTER_FULL = 3
        ///SMT_LOBBY_CONFIRM_DELETE_CHARACATER = 4
        ///SMT_LOBBY_DELETE_CHARACATER_COMPLETE = 5
        ///SMT_LOBBY_CONFIRM_CANCEL_DELETE_CHARACATER = 6
        ///SMT_LOBBY_CANCEL_DELETE_CHARACATER_COMPLETE = 7
        ///SMT_LOBBY_DUPLICATE_NAME = 8
        ///SMT_LOBBY_CHARACTER_NAME_LIMIT = 9
        ///SMT_LOBBY_CHARACTER_NAME_FORBIDDEN = 10
        ///SMT_LOBBY_CHARACTER_NAME_OK = 11
        ///SMT_LOBBY_CONFIRM_CREATE_CHARACTER = 12
        ///SMT_LOBBY_CHARACTER_NAME_SPECIAL_LETT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string smt_311380 {
            get {
                return ResourceManager.GetString("smt_311380", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMT_UNDEFINED = 0
        ///SMT_LOBBY_CANNOT_CONNECT = 1
        ///SMT_LOBBY_CONFIRM_DISCONNECT = 2
        ///SMT_LOBBY_CHARACTER_FULL = 3
        ///SMT_LOBBY_CONFIRM_DELETE_CHARACATER = 4
        ///SMT_LOBBY_DELETE_CHARACATER_COMPLETE = 5
        ///SMT_LOBBY_CONFIRM_CANCEL_DELETE_CHARACATER = 6
        ///SMT_LOBBY_CANCEL_DELETE_CHARACATER_COMPLETE = 7
        ///SMT_LOBBY_DUPLICATE_NAME = 8
        ///SMT_LOBBY_CHARACTER_NAME_LIMIT = 9
        ///SMT_LOBBY_CHARACTER_NAME_FORBIDDEN = 10
        ///SMT_LOBBY_CHARACTER_NAME_OK = 11
        ///SMT_LOBBY_CONFIRM_CREATE_CHARACTER = 12
        ///SMT_LOBBY_CHARACTER_NAME_SPECIAL_LETT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string smt_311738 {
            get {
                return ResourceManager.GetString("smt_311738", resourceCulture);
            }
        }
    }
}
